# -*- coding: utf-8 -*-
"""rubic_based_scoring.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aj_OuJbS03x3QRiD9dYa3hQT1iz1tuv6

1. Import Libraries
"""

import numpy as np
import pandas as pd

# Visualization libraries
import matplotlib.pyplot as plt
import seaborn as sns

# ML libraries
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Settings
sns.set(style="whitegrid")
plt.rcParams["figure.figsize"] = (8, 5)

"""2. Load Training Dataset"""

# Upload viva_train_dataset.csv to Colab manually
df = pd.read_csv("viva_train_dataset.csv")

df.head()

"""3. Basic Data Understanding"""

df.shape
df.info()
df.isnull().sum()
df.describe()

"""4. Exploratory Data Analysis (EDA)"""

sns.histplot(df["total_score"], bins=20, kde=True)
plt.title("Distribution of Total Viva Scores")
plt.show()

questions = ['q1_score','q2_score','q3_score','q4_score','q5_score']

for q in questions:
    sns.histplot(df[q], bins=15, kde=True)
    plt.title(f"Distribution of {q}")
    plt.show()

sns.boxplot(data=df[questions])
plt.title("Score Spread Across Viva Questions")
plt.show()

sns.boxplot(x="final_grade", y="total_score", data=df)
plt.title("Total Score Distribution by Final Grade")
plt.show()

sns.countplot(x="final_grade", data=df)
plt.title("Grade Distribution")
plt.show()

sns.heatmap(df[questions + ['total_score']].corr(),
            annot=True, cmap="coolwarm", fmt=".2f")
plt.title("Correlation Between Question Scores & Total Score")
plt.show()

sns.pairplot(df[questions + ['total_score']])
plt.show()

avg_scores = df[questions].mean()

avg_scores.plot(kind="bar")
plt.title("Average Contribution of Each Question")
plt.ylabel("Average Score")
plt.show()

sns.violinplot(data=df[questions])
plt.title("Violin Plot of Question Score Distributions")
plt.show()

"""5. Feature Selection"""

X = df[['q1_score','q2_score','q3_score','q4_score','q5_score']]
y = df['total_score']

print("First 5 rows of X:")
display(X.head())
print("\nFirst 5 rows of y:")
display(y.head())

"""6. Train-Test Split"""

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

"""7. Model Training (Linear Regression)"""

model = LinearRegression()
model.fit(X_train, y_train)

"""8. Model Evaluation"""

y_pred = model.predict(X_test)

print("MAE:", mean_absolute_error(y_test, y_pred))
print("MSE:", mean_squared_error(y_test, y_pred))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred)))
print("R² Score:", r2_score(y_test, y_pred))

plt.scatter(y_test, y_pred)
plt.xlabel("Actual Total Score")
plt.ylabel("Predicted Total Score")
plt.title("Actual vs Predicted Viva Scores")
plt.show()

residuals = y_test - y_pred

sns.histplot(residuals, bins=20, kde=True)
plt.title("Residual Error Distribution")
plt.show()

"""9. Grade Prediction Function"""

def assign_grade(score):
    if score >= 40:
        return "A"
    elif score >= 30:
        return "B"
    elif score >= 25:
        return "C"
    else:
        return "Fail"

"""10. Test Dataset Prediction (Final Output)"""

# Load test dataset
test_df = pd.read_csv("viva_test_dataset.csv")

# Predict total score
test_df["predicted_total_score"] = model.predict(test_df)

# Predict grade
test_df["predicted_grade"] = test_df["predicted_total_score"].apply(assign_grade)

test_df.head()

"""11. Save Predictions"""

test_df.to_csv("viva_predictions.csv", index=False)

"""12. Save Predictions as Pickle"""

test_df.to_pickle("viva_predictions.pkl")